language: c++
compiler: clang
env: CMAKE_BUILD_TYPE=RELEASE

branches:
    only:
        - master

os:
    - linux
    - osx

osx_image: xcode8.2
sudo: true

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - boost-latest
        packages:
            - cmake
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-locale1.55-dev
            - libssl-dev
            - libpng-dev
            - libjpeg-dev
            - clang-3.8
            - g++-5
            - gcc-5

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update
        brew install openssl
        brew install jpeg-turbo
        export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update -qq
    fi

install: |
    if [ "$CXX" = "g++" ]; then
        export CXX="g++-5"
        export CC="gcc-5"
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then
        export CXX="clang++-3.8"
        export CC="clang-3.8"
    fi

script: |
    mkdir build
    cd build
    cmake ..
    cmake --build .
    cd ..
    ./build/run_tests
